spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    platform: h2
    initialization-mode: always # Cria o schema automaticamente
  jpa:
    hibernate:
      ddl-auto: update  # Atualiza o schema automaticamente ao reiniciar
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
          import_files_sql_exceptions:
            fail_on_error: true
    show-sql: false  # Mostra as queries SQL no console
